imports:
    - { resource: ../nelmio/phones.yaml }
    - { resource: ../nelmio/phone.yaml }
    - { resource: ../nelmio/authentication.yaml }
nelmio_api_doc:
    documentation:
        info:
            title: Bilmo API
            description: This is an awesome app who allow you to get phones information, to stock information about your company and also about your client (/api/users endpoint)
            version: 1.0.0
        components:
            securitySchemes:
                Bearer:
                    type: http
                    scheme: bearer
                    bearerFormat: JWT
        security:
            -   Bearer: [ ]
        paths:
            '/api/phones': '%nelmio_phones%'
            '/api/phones/{id}': '%nelmio_phone%'
            '/api/login_check': '%nelmio_authentication%'
        tags:
            -
                name: authentication
                description: Authentication on this API
            -
                name: phone
                description: Phones proposed in catalog

    areas: # to filter documented areas
        path_patterns:
            - ^/api(?!/doc$) # Accepts routes under /api except /api/doc
        host_patterns: # document only routes with a host of the form api.*
            - ^api\.
