parameters:
    nelmio_phones:
        get:
            tags: [ phone ]
            summary: 'Get phones list'
            description: 'Get phones list'
            responses:
                '200':
                    description: 'OK'
                '401':
                    description: 'Unauthorized'